services:
  # Serviço MySQL
  mysql:
    image: mysql:8.0
    container_name: emprestimo-livros-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: dbEmprestimoLivro
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./banco_de_dados/docker-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: emprestimo-livros-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_DATABASE_NAME: dbEmprestimoLivro
      SECRET_JWT: super-secret-jwt-key-change-in-production
      PORT: 3000
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./backend/src:/app/src
      - ./backend/features:/app/features

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
